baseURL = "https://1337misterzero.github.io/blog"
languageCode = "en-us"
title = "zero"
theme = "PaperMod"

[params]
  env = "production"
  author = "zero"
  description = "Notes from the edge."
  defaultTheme = "dark"
  disableThemeToggle = true
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowToc = true
  TocOpen = false
  ShowShareButtons = false

  [params.homeInfoParams]
    Title = "zero"
    Content = "systems / networks / code / noise"

[[menu.main]]
  name = "posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  name = "projects"
  url = "/projects/"
  weight = 20

[[menu.main]]
  name = "about"
  url = "/about/"
  weight = 30
