baseURL = "https://1337misterzero.github.io/blog/"
languageCode = "en-us"
title = "zero_"
paginate = 8

[params]
description = "systems / networks / code / linux / noise"
author = "zero"
images = []

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
taxonomy = ["HTML"]
term = ["HTML"]
