baseURL = 'https://1337misterzero.github.io/blog/'
title = 'zero'
defaultContentLanguage = 'en'
mainSections = ['posts']

[params]
description = 'systems / networks / code / linux / security / engineering'
author = 'zero'
walineServerURL = ''

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ['HTML', 'RSS']
section = ['HTML', 'RSS']
