baseURL = 'https://1337misterzero.github.io/blog/'
title = 'zero'
defaultContentLanguage = 'en'
mainSections = ['posts']

[params]
description = 'systems / networks / code / linux / security / engineering'
author = 'zero'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ['HTML', 'RSS']
section = ['HTML', 'RSS']


# Set this after deploying your Waline server.
# Anonymous comments and GitHub login are enabled by Waline.
[params]
walineServerURL = ''
