# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: 1337misterzero/blog
  branch: main
  auth_methods:
    - token

site_url: https://1337misterzero.github.io/blog/
display_url: https://1337misterzero.github.io/blog/

media_folder: /static/images
public_folder: /blog/images

collections:

  - name: posts
    label: Posts
    label_singular: Post
    folder: /content/posts
    create: true
    delete: true
    extension: md
    format: yaml-frontmatter
    slug: "{{slug}}"

    fields:

      - name: title
        label: Title
        widget: string

      - name: date
        label: Date
        widget: datetime
        format: "YYYY-MM-DDTHH:mm:ssZ"

      - name: description
        label: Description
        widget: text
        required: false

      - name: tags
        label: Tags
        widget: list
        required: false
        field:
          label: Tag
          name: tag
          widget: string

      - name: body
        label: Content
        widget: markdown

  - name: pages
    label: Pages
    label_singular: Page
    files:

      - name: about
        label: About
        file: /content/about.md
        fields:

          - name: title
            label: Title
            widget: string

          - name: description
            label: Description
            widget: text
            required: false

          - name: body
            label: Content
            widget: markdown
